from __future__ import annotations

from forgeflow_api.domain.models import ModelCatalogEntry


def default_model_catalog() -> list[ModelCatalogEntry]:
    return [
        ModelCatalogEntry(
            id="catalog_flux2_klein_4b",
            label="FLUX.2 klein 4B",
            normalized_id="black-forest-labs/FLUX.2-klein-4B",
            source_kind="local_hf_diffusers",
            capabilities=["image_generation", "image_editing"],
            metadata={
                "family": "FLUX.2",
                "release_year": 2026,
                "runtime_options": ["local_hf_diffusers", "api"],
                "quantization": "nf4",
                "local_profile": {
                    "fits_rtx_3090": True,
                    "vram_gb_estimate": 13,
                    "notes": "Targets RTX 3090/4070 class GPUs; supports text-to-image and image-to-image multi-reference editing.",
                },
                "recommended_for": ["text_to_image", "image_edit"],
            },
        ),
        ModelCatalogEntry(
            id="catalog_flux2_klein_9b",
            label="FLUX.2 klein 9B",
            normalized_id="black-forest-labs/FLUX.2-klein-9B",
            source_kind="local_hf_diffusers",
            capabilities=["image_generation", "image_editing"],
            metadata={
                "family": "FLUX.2",
                "release_year": 2026,
                "runtime_options": ["local_hf_diffusers", "api"],
                "quantization": "nf4",
                "local_profile": {
                    "fits_rtx_3090": True,
                    "vram_gb_estimate": 22,
                    "notes": "Higher quality local/API option; prefer NF4 with CPU/offload headroom on 24GB GPUs.",
                },
                "recommended_for": ["text_to_image", "image_edit"],
            },
        ),
        ModelCatalogEntry(
            id="catalog_qwen_image_2",
            label="Qwen Image 2.0",
            normalized_id="Qwen/Qwen-Image-2.0",
            source_kind="local_hf_diffusers",
            capabilities=["image_generation", "image_editing"],
            metadata={
                "family": "Qwen Image",
                "release_year": 2026,
                "runtime_options": ["local_hf_diffusers", "api"],
                "quantization": "nf4",
                "local_profile": {
                    "fits_rtx_3090": "conditional",
                    "notes": "Unified high-fidelity generation and precise image editing candidate; use quantized/offloaded runtime.",
                },
                "recommended_for": ["image_edit", "text_to_image"],
            },
        ),
        ModelCatalogEntry(
            id="catalog_qwen_image_edit_2511",
            label="Qwen Image Edit 2511",
            normalized_id="Qwen/Qwen-Image-Edit-2511",
            source_kind="local_hf_diffusers",
            capabilities=["image_editing"],
            metadata={
                "family": "Qwen Image",
                "release_year": 2026,
                "runtime_options": ["local_hf_diffusers", "api"],
                "quantization": "nf4",
                "local_profile": {
                    "fits_rtx_3090": "conditional",
                    "notes": "Edit-focused preset for precision edits and structure-preserving transformations.",
                },
                "recommended_for": ["image_edit"],
            },
        ),
        ModelCatalogEntry(
            id="catalog_z_image",
            label="Z-Image",
            normalized_id="ZhipuAI/Z-Image",
            source_kind="local_hf_diffusers",
            capabilities=["image_generation"],
            metadata={
                "family": "Z-Image",
                "release_year": 2026,
                "runtime_options": ["local_hf_diffusers", "api"],
                "quantization": "nf4",
                "local_profile": {
                    "fits_rtx_3090": True,
                    "parameter_count": "6B",
                    "notes": "Efficient generation preset for consumer GPU workflows.",
                },
                "recommended_for": ["text_to_image"],
            },
        ),
        ModelCatalogEntry(
            id="catalog_z_image_edit",
            label="Z-Image Edit",
            normalized_id="ZhipuAI/Z-Image-Edit",
            source_kind="local_hf_diffusers",
            capabilities=["image_editing"],
            metadata={
                "family": "Z-Image",
                "release_year": 2026,
                "runtime_options": ["local_hf_diffusers", "api"],
                "quantization": "nf4",
                "local_profile": {
                    "fits_rtx_3090": True,
                    "parameter_count": "6B",
                    "notes": "Efficient edit preset for instruction-guided image modifications.",
                },
                "recommended_for": ["image_edit"],
            },
        ),
        ModelCatalogEntry(
            id="catalog_qwen3_32b",
            label="Qwen3 32B Instruct",
            normalized_id="Qwen/Qwen3-32B-Instruct",
            source_kind="local_hf_transformers",
            capabilities=["planner_text", "text_chat"],
            metadata={
                "family": "Qwen3",
                "release_year": 2026,
                "runtime_options": ["local_hf_transformers", "ollama", "vllm"],
                "quantization": "nf4",
                "local_profile": {"fits_rtx_3090": True, "notes": "24GB-class local planning/chat preset."},
                "recommended_for": ["workflow"],
            },
        ),
        ModelCatalogEntry(
            id="catalog_deepseek_r1_qwen_32b",
            label="DeepSeek R1 Distill Qwen 32B",
            normalized_id="deepseek-ai/DeepSeek-R1-Distill-Qwen-32B",
            source_kind="local_hf_transformers",
            capabilities=["planner_text", "text_chat"],
            metadata={
                "family": "DeepSeek R1 Distill",
                "release_year": 2026,
                "runtime_options": ["local_hf_transformers", "ollama", "vllm"],
                "quantization": "nf4",
                "local_profile": {"fits_rtx_3090": True, "notes": "Reasoning-oriented local workflow option."},
                "recommended_for": ["workflow"],
            },
        ),
        ModelCatalogEntry(
            id="catalog_gpt_oss_20b",
            label="GPT OSS 20B",
            normalized_id="openai/gpt-oss-20b",
            source_kind="local_hf_transformers",
            capabilities=["planner_text", "text_chat"],
            metadata={
                "family": "GPT OSS",
                "release_year": 2026,
                "runtime_options": ["local_hf_transformers", "ollama", "vllm"],
                "quantization": "nf4",
                "local_profile": {"fits_rtx_3090": True, "notes": "Agentic/coding-friendly local option."},
                "recommended_for": ["workflow"],
            },
        ),
        ModelCatalogEntry(
            id="catalog_kimi_k25",
            label="Kimi K2.5",
            normalized_id="moonshotai/kimi-k2.5",
            source_kind="api_generic",
            capabilities=["planner_text", "text_chat", "vision_review"],
            metadata={
                "family": "Kimi",
                "release_year": 2026,
                "runtime_options": ["nvidia"],
                "recommended_for": ["workflow", "vision_review"],
            },
        ),
        ModelCatalogEntry(
            id="catalog_minimax_m25",
            label="MiniMax M2.5",
            normalized_id="minimax/minimax-m2.5:free",
            source_kind="api_openrouter",
            capabilities=["planner_text", "text_chat"],
            metadata={
                "family": "MiniMax",
                "release_year": 2026,
                "runtime_options": ["openrouter"],
                "recommended_for": ["workflow"],
            },
        ),
    ]
